spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing-app
    username: postgres
    password: 123

  jpa:
    defer-datasource-initialization: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
